FROM developmentseed/caffe-segnet:gpu
MAINTAINER anand@developmentseed.org

RUN pip install boto3

ENV DEBIAN_FRONTEND noninteractive
RUN curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash - && \
    sudo apt-get install -y nodejs build-essential

ADD . /workspace
WORKDIR /workspace

RUN npm install

# Expose demo server port
EXPOSE 5000

ENTRYPOINT ["segnet/train"]

