FROM developmentseed/caffe-segnet:gpu
MAINTAINER anand@developmentseed.org

RUN pip install boto3

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && \
    apt-get -qq update && \
    apt-get install -y nodejs npm && \
    update-alternatives --install /usr/bin/node node /usr/bin/nodejs 10

ADD . /workspace
WORKDIR /workspace

RUN npm install

# Expose demo server port
EXPOSE 5000

ENTRYPOINT ["segnet/train"]

