FROM developmentseed/caffe-segnet:gpu
MAINTAINER anand@developmentseed.org

ENV DEBIAN_FRONTEND noninteractive
RUN curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash - && \
    sudo apt-get install -y nodejs build-essential

RUN pip install boto3 && \
    pip install protobuf

ADD package.json /workspace/package.json
RUN npm install

ADD . /workspace
WORKDIR /workspace

# Expose demo server port
EXPOSE 5000

ENTRYPOINT ["segnet/train"]

