#!/usr/bin/env node

var fs = require('fs-extra')
var path = require('path')
var spawnSync = require('child_process').spawnSync
var argv = require('minimist')(process.argv.slice(2))

var computeStats = path.join(__dirname, 'compute_bn_statistics.py')
var runTest = path.join(__dirname, 'test_segmentation.py')

if (!argv.train || !argv.weights || !argv.classes || !argv.output) {
  console.error('Usage: ' + process.argv.slice(0, 2).join(' ') + ' train.prototxt weights.caffemodel -o /path/to/results/output')
  process.exit(1)
}

var train = path.resolve(argv.train)
var weights = path.resolve(argv.weights)
var classes = path.resolve(argv.classes)
var output = path.resolve(argv.output)

// guess the inference.prototxt filename
var inference = argv.inference || train.replace('train', 'inference')

// dir for outputting the BN-stats-infused weights
var inferenceDir = weights.replace('.caffemodel', '.inference')

fs.mkdirSync(inferenceDir)

spawnSync('python', [
  computeStats,
  train,
  weights,
  inferenceDir
], { stdio: 'inherit' })

spawnSync('python', [
  runTest,
  '--model', inference,
  '--weights', path.join(inferenceDir, 'test_weights.caffemodel'),
  '--classes', classes,
  '--output', output
], { stdio: 'inherit' })

fs.copySync(path.join(__dirname, 'dist'), output)

console.log('Done!')

