FROM developmentseed/caffe-segnet:cpu
MAINTAINER anand@developmentseed.org

RUN pip install flask

ADD . /workspace

EXPOSE 5000

ENTRYPOINT ["python", "demo.py", "--cpu-mode"]
CMD ["--model", "/data/segnet_deploy.prototxt", "--weights", "/data/test_weights.caffemodel", "--classes", "/data/classes.json"]

